_wandb:
    value:
        cli_version: 0.23.0
        e:
            c9n0cm4fp5ha5zx4iktdd117fbzagvk4:
                args:
                    - --bf16
                    - "True"
                    - --lang_encoder_path
                    - /mnt/home/zhoujunjie/models/Llama-2-7b-chat-hf
                    - --tokenizer_path
                    - /mnt/home/zhoujunjie/models/Llama-2-7b-chat-hf
                    - --pretrained_visual_encoder
                    - /mnt/home/zhoujunjie/models/Reg2RG/RadFM_vit3d.pth
                    - --pretrained_adapter
                    - /mnt/home/zhoujunjie/models/Reg2RG/RadFM_perceiver_fc.pth
                    - --data_folder
                    - /mnt2/ct/RadGenome-ChestCT/dataset/train_preprocessed
                    - --mask_folder
                    - /mnt2/ct/RadGenome-ChestCT/dataset/train_region_mask
                    - --report_file
                    - /mnt2/ct/RadGenome-ChestCT/dataset/radgenome_files/train_region_report.csv
                    - --monai_cache_dir
                    - /mnt2/ct/RadGenome-ChestCT/cache
                    - --output_dir
                    - /mnt/home/zhoujunjie/Reg2RG/outputs/Reg2RG_radgenome
                    - --deepspeed
                    - /mnt/home/zhoujunjie/Reg2RG/ds_configs/stage2.json
                    - --per_device_train_batch_size
                    - "1"
                    - --num_train_epochs
                    - "10"
                    - --gradient_accumulation_steps
                    - "8"
                    - --evaluation_strategy
                    - "no"
                    - --save_strategy
                    - epoch
                    - --save_total_limit
                    - "3"
                    - --learning_rate
                    - "5e-5"
                    - --weight_decay
                    - "0.0"
                    - --warmup_steps
                    - "20"
                    - --lr_scheduler_type
                    - constant_with_warmup
                    - --dataloader_num_workers
                    - "8"
                    - --run_name
                    - Reg2RG_radgenome
                    - --logging_steps
                    - "1"
                    - --logging_strategy
                    - steps
                    - --report_to
                    - wandb
                codePath: src/train_radgenome.py
                codePathLocal: src/train_radgenome.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "982820896768"
                        used: "905692258304"
                email: menging1122@gmail.com
                executable: /mnt/home/zhoujunjie/miniconda3/envs/reg2rg/bin/python3.9
                git:
                    commit: 1783aed6fe6aefdd7f9f91646764913b1d1844ab
                    remote: https://gh.llkk.cc/https://github.com/junjiezhou1122/Reg2RG.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-c9302b6e-ead7-2270-4912-e103a3e1fe27
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-3fac1ae0-4e3b-9741-d96f-8294bca49dc6
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-87281244-bb68-c523-cc5a-0ddb5190292d
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-fc998b2b-4a24-9f94-0c82-62c79cd5f63f
                host: super-Super-Server
                memory:
                    total: "134747009024"
                os: Linux-5.15.0-78-generic-x86_64-with-glibc2.31
                program: /mnt/home/zhoujunjie/Reg2RG/src/train_radgenome.py
                python: CPython 3.9.25
                root: /mnt/home/zhoujunjie/Reg2RG
                startedAt: "2025-11-21T03:59:47.200197Z"
                writerId: c9n0cm4fp5ha5zx4iktdd117fbzagvk4
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 48
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 48
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 7
                - 13
                - 66
            "4": 3.9.25
            "5": 0.23.0
            "6": 4.28.1
            "12": 0.23.0
            "13": linux-x86_64
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
auto_find_batch_size:
    value: false
bf16:
    value: true
bf16_full_eval:
    value: false
cache_dir:
    value: None
data_seed:
    value: None
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 8
dataloader_pin_memory:
    value: true
ddp_bucket_cap_mb:
    value: None
ddp_find_unused_parameters:
    value: None
ddp_timeout:
    value: 1800
debug:
    value: '[]'
deepspeed:
    value: /mnt/home/zhoujunjie/Reg2RG/ds_configs/stage2.json
disable_tqdm:
    value: false
do_eval:
    value: false
do_predict:
    value: false
do_train:
    value: false
eval_accumulation_steps:
    value: None
eval_batch_size:
    value: 8
eval_delay:
    value: 0
eval_steps:
    value: None
evaluation_strategy:
    value: "no"
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: '[]'
fsdp_config:
    value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: None
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: false
greater_is_better:
    value: None
group_by_length:
    value: false
half_precision_backend:
    value: cuda_amp
hub_model_id:
    value: None
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: None
label_smoothing_factor:
    value: 0
learning_rate:
    value: 5e-05
length_column_name:
    value: length
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /mnt/home/zhoujunjie/Reg2RG/outputs/Reg2RG_radgenome/runs/Nov21_11-57-56_super-Super-Server
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 1
logging_strategy:
    value: steps
lr_scheduler_type:
    value: constant_with_warmup
max_grad_norm:
    value: 1
max_steps:
    value: -1
metric_for_best_model:
    value: None
mp_parameters:
    value: ""
no_cuda:
    value: false
num_train_epochs:
    value: 10
optim:
    value: adamw_torch
optim_args:
    value: None
output_dir:
    value: /mnt/home/zhoujunjie/Reg2RG/outputs/Reg2RG_radgenome
overwrite_output_dir:
    value: false
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 1
per_gpu_eval_batch_size:
    value: None
per_gpu_train_batch_size:
    value: None
pin_memory:
    value: true
prediction_loss_only:
    value: false
push_to_hub:
    value: false
push_to_hub_model_id:
    value: None
push_to_hub_organization:
    value: None
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_unused_columns:
    value: true
report_to:
    value: '[''wandb'']'
resume_from_checkpoint:
    value: None
run_name:
    value: Reg2RG_radgenome
save_on_each_node:
    value: false
save_safetensors:
    value: false
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: 3
seed:
    value: 42
sharded_ddp:
    value: '[]'
skip_memory_metrics:
    value: true
tf32:
    value: None
torch_compile:
    value: false
torch_compile_backend:
    value: None
torch_compile_mode:
    value: None
torchdynamo:
    value: None
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: None
train_batch_size:
    value: 1
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
warmup_ratio:
    value: 0
warmup_steps:
    value: 20
weight_decay:
    value: 0
xpu_backend:
    value: None
